---
title: "Meta Data of Marine Research Protocol"
output:
  pdf_document:
    number_sections: no
    toc: yes
    toc_depth: 1
  html_document:
    theme: lumen
    toc: yes
    toc_depth: '1'
Author: Juliano Palacios-Abrantes; Core Group
---

#Executive Summary 

#Introduction
Protocol for Data Input

##General Guide
- No accents
- Entries can be in both Spanish and English (except stated otherwise) 

## Abaout the Metadata fields
All fields x possible things:

1. They can be *mandatory* or *optional*
2. They can be *fixed* values or open *section*

- Fixed: the inputs are part of a select group and no other value is allowed.
- Open: Inpus can be whatever the author decides

3. There could be *multiple values* or a *single one*


```{r Template, echo =F, eval=F}

Data <- read.csv("./Template.csv")

```

#Metadata Fields

##MMID
- Mandatory / Fixed / Single

This is the ID of each data entry. It is important to input this number correcly after the last data point to keep consistency.

##Short Title
- Mandatory / Open / Single

Short informative title of the dataset. There are no limitations on the number of words but please make it short.

###Example
Shark Survey in the Pacific Coast between 1990-2000.
*Original dataset title:* Shark Survey in the Mexican Pacific Coast, between Oaxaca and Chiapas State using georeference devices between 1990-2000

##Keywords
- Mandatory / Open / Multiple / Spanish

Words in spanish that best describe the subject or/and dataset. These words will be useful to search data. There is no words limitation. Can be both words and numbers.

**Special Situation:** When a row contains more than one datasets the keywords must have all the datasets available in te repository. 

###Example
For a "normal" row, the keywords could look something like this:
Pescado; Tuna; Pescador; Esfuerzo; Sinaloa; Temperatura; Mapa; 1:250000

**Special Situation:** For 

##Author

Author of the dataset responsible for giving support on the dataset. Mandatory
-	In case there is non, whoever is uploading the data should be the “author”

###Example
Andres Cisneros; a.cisneros@oceans.ubc.ca

##Institution

Institution or organization associated with the author. Not mandatory

###Example
University of British Columbia

##Dataset Available
Is the dataset publically available for anyone to use? Mandatory
1.	Yes, it is public and of easy access
a.	A dataset that lives on a webpage and you can download from it
2.	Yes, it is public domain. However, is not directly available or has some type of limitation (nationality, request, etc.) 
a.	A public dataset that you need to file in a request to have access 
3.	No, it is a private dataset
a.	A fisherman cooperative sampling data

##Subject Name

Common species name, if known; otherwise, subject studied. Mandatory
•	Limited to 2 words
•	Has to be in Spanish

###Example
Atrina maura, Tuna, shark, callo de hacha, panga,  pH, Sinaloa 

##Area

The broader category of where the data was generated. Options are fixed but can’t be multiple selection. Mandatory.
•	National (When data applies for the whole country)
•	Atlantic Ocean
•	Pacific Ocean
•	Freshwater/Terrestrial (When data is related to freshwater and or land ecosystems)

##Region

A less broad location of the data (if possible). Options are fixed and can be multiple. Not mandatory
•	Gulf of California
•	Northwest Pacific
•	South Pacific
•	Gulf of Tehuantepec
•	Yucatan Peninsula / Mar Caribe
•	West Gulf of Mexico.

##Location

The more specific level of data localization. It can range from a specific state to georeferenced data. It is an open category with no limitations. Not mandatory

###Example
Laguna de Altata, Western Pacific of Baja California Sur, Shape file, Georeferenced.

##Start and End Year

The Starting year and end year of the time series. Mandatory

##Temporal Resolution

What is the temporal resolution of the data? Fixed values. Mandatory
•	Annual
•	Monthly
•	Semester
•	Weekly
•	Daily
•	Seconds

##Data Time Points

This section refers to the amount of data points available in the dataset. It is related to the start and end year.

###Example
The dataset start year in 2010, the end year is 2015 and the frequency is yearly. However, there is only 3 data points because data from 2012 and 2013 are missing. 

##Unit Type
### Definition
They type of unit used. Fixed Values
- Area
- Size
- Weight
- Values
- Counts
- Index
- Temperature
- Concentration
- pH
- Depth

##Spatial Resolution
### Definition
What is the spatial resolution of the data
### Example
It could be a "state", it could be coordinates.

##Dataset Title
### Definition
Original name of dataset (the data specifically, not the source or repository where it was published).
### Example
- Producción Annual de Octopus Nei.
- PARTICIPACIÓN DE LA ACUACULTURA EN EL VALOR DE LA PRODUCCIÓN PESQUERA NACIONAL
- Personal Ocupado en el Sector Pesca

This are all datasets that are found inside the Anuario Estadístico de Acuacultura y Pesca 2013

##Compilation Title
### Definition
Name of the document or repository where data is presented
### Example
- FAO fisheries quantity
- Anuario Estadístico SAGARPA
- Censo Poblacional de INEGI

This are all mayor aggregations/spurces of data
##Publication Year
### Definition
Year in which the dataset was published
### Example
1998
##Reference
Link or address of where the data can be found

### Example
www.repositoryonlinewheredatalives.com or Meta-dataset 

##Available in Metadata
If the data is or not part of the Meta-dataset data repository

##Metadata Name
In case the data set is in the Meta-data, then what's the name of it?

##User Contact
Name and email of person who identified and/or added the data to the Metadata

##Institution Type
The type of institution that generated the dataset (corresponds to "Institution" field)

##Research Fund
Who funded the data collection

##Research Field
What was the main reason why the data was  gathered 

##Social-Economic Interaction
What type of social-ecological interaction is this data an indicator for

##Data-Uncertanty
What is the quality of the data?


